### ISSUE TITLE
Personal access token is required for release-please-action.

### ISSUE THREAD

**Issue by pysan3** [nvim-neorocks/sample-luarocks-plugin#1]
As stated [here](https://github.com/google-github-actions/release-please-action#github-credentials) release please needs a separate token to enable action to be invoked _after_ release-please.

The luarocks release action will be invoked after release-please so we need to do this step.

Here are the steps that worked for me.

1. Go to your own [user settings](https://github.com/settings/profile).
1. `Settings` > `Developer settings` > `Personal access tokens` > `Tokens (classic)` > `Generate new token`
2. Create a new token with `repo`, `workflow`, `codespace` enabled.
3. Copy the generated token. (This is the only place you can copy it. Don't loose it!)

---

1. Go to project.
2. `Settings` > `Secrets and variables` > `Actions` > `New repository secret`
3. Make a new secret with `REALEASE_PLEASE_TOKEN` and the value being what you copied above.
4. Specify `with:token` like below.

```yaml

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: <your repo name>
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
```
